[2024-11-05T16:46:08.209+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-05T16:46:08.254+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data_pipeline_v2.clean_and_transfer_csv_files.clean_and_transfer_customer manual__2024-11-05T16:46:02.792522+00:00 [queued]>
[2024-11-05T16:46:08.272+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data_pipeline_v2.clean_and_transfer_csv_files.clean_and_transfer_customer manual__2024-11-05T16:46:02.792522+00:00 [queued]>
[2024-11-05T16:46:08.272+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2024-11-05T16:46:08.304+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): clean_and_transfer_csv_files.clean_and_transfer_customer> on 2024-11-05 16:46:02.792522+00:00
[2024-11-05T16:46:08.338+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=41282) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-05T16:46:08.363+0000] {standard_task_runner.py:63} INFO - Started process 41339 to run task
[2024-11-05T16:46:08.367+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_data_pipeline_v2', 'clean_and_transfer_csv_files.clean_and_transfer_customer', 'manual__2024-11-05T16:46:02.792522+00:00', '--job-id', '3613', '--raw', '--subdir', 'DAGS_FOLDER/etl2.py', '--cfg-path', '/tmp/tmpdk19532i']
[2024-11-05T16:46:08.373+0000] {standard_task_runner.py:91} INFO - Job 3613: Subtask clean_and_transfer_csv_files.clean_and_transfer_customer
[2024-11-05T16:46:08.475+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_data_pipeline_v2.clean_and_transfer_csv_files.clean_and_transfer_customer manual__2024-11-05T16:46:02.792522+00:00 [running]> on host 71321b93f95e
[2024-11-05T16:46:08.736+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data_pipeline_v2' AIRFLOW_CTX_TASK_ID='clean_and_transfer_csv_files.clean_and_transfer_customer' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T16:46:02.792522+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T16:46:02.792522+00:00'
[2024-11-05T16:46:08.738+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-05T16:46:08.749+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-11-05T16:46:08.757+0000] {base.py:84} INFO - Using connection ID 'my-gcp-conn' for task execution.
[2024-11-05T16:46:10.298+0000] {gcs.py:344} INFO - File downloaded to /tmp/customer.csv
[2024-11-05T16:46:10.688+0000] {gcs.py:557} INFO - File /tmp/cleaned_customer.csv uploaded to customer.csv in storage-madt-finalproject bucket
[2024-11-05T16:46:10.689+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-05T16:46:10.689+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-05T16:46:10.697+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl_data_pipeline_v2, task_id=clean_and_transfer_csv_files.clean_and_transfer_customer, execution_date=20241105T164602, start_date=20241105T164608, end_date=20241105T164610
[2024-11-05T16:46:10.761+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-05T16:46:10.783+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T16:46:10.789+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
