[2024-09-29T14:33:13.381+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-29T14:33:13.448+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.create_dataset scheduled__2024-09-14T00:00:00+00:00 [queued]>
[2024-09-29T14:33:13.501+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.create_dataset scheduled__2024-09-14T00:00:00+00:00 [queued]>
[2024-09-29T14:33:13.510+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-09-29T14:33:13.570+0000] {taskinstance.py:2327} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_dataset> on 2024-09-14 00:00:00+00:00
[2024-09-29T14:33:13.618+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'create_dataset', 'scheduled__2024-09-14T00:00:00+00:00', '--job-id', '2337', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpl8ze2ax3']
[2024-09-29T14:33:13.631+0000] {standard_task_runner.py:91} INFO - Job 2337: Subtask create_dataset
[2024-09-29T14:33:13.629+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=25491) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T14:33:13.641+0000] {standard_task_runner.py:63} INFO - Started process 25576 to run task
[2024-09-29T14:33:13.807+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.create_dataset scheduled__2024-09-14T00:00:00+00:00 [running]> on host 71321b93f95e
[2024-09-29T14:33:14.133+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='create_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-09-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-14T00:00:00+00:00'
[2024-09-29T14:33:14.135+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-29T14:33:14.167+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-29T14:33:14.187+0000] {base.py:84} INFO - Using connection ID 'my-gcp-conn' for task execution.
[2024-09-29T14:33:14.493+0000] {bigquery.py:470} INFO - datasetId was not specified in `dataset_reference`. Will use default value finalproject_data.
[2024-09-29T14:33:14.493+0000] {bigquery.py:470} INFO - projectId was not specified in `dataset_reference`. Will use default value madt-finalproject.
[2024-09-29T14:33:14.494+0000] {bigquery.py:481} INFO - Creating dataset: finalproject_data in project: madt-finalproject 
[2024-09-29T14:33:15.286+0000] {bigquery.py:2045} INFO - Dataset finalproject_data already exists.
[2024-09-29T14:33:15.388+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-29T14:33:15.420+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_dataset, execution_date=20240914T000000, start_date=20240929T143313, end_date=20240929T143315
[2024-09-29T14:33:15.971+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-29T14:33:16.126+0000] {taskinstance.py:3482} INFO - 9 downstream tasks scheduled from follow-on schedule check
[2024-09-29T14:33:16.147+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
