[2024-09-29T09:09:19.449+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-29T09:09:19.537+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.create_dataset scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-09-29T09:09:19.640+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.create_dataset scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-09-29T09:09:19.641+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-09-29T09:09:21.087+0000] {taskinstance.py:2327} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_dataset> on 2024-05-30 00:00:00+00:00
[2024-09-29T09:09:21.248+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'create_dataset', 'scheduled__2024-05-30T00:00:00+00:00', '--job-id', '314', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpam_hsw2n']
[2024-09-29T09:09:21.267+0000] {standard_task_runner.py:91} INFO - Job 314: Subtask create_dataset
[2024-09-29T09:09:21.259+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=30783) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T09:09:21.284+0000] {standard_task_runner.py:63} INFO - Started process 30888 to run task
[2024-09-29T09:09:21.620+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.create_dataset scheduled__2024-05-30T00:00:00+00:00 [running]> on host 71321b93f95e
[2024-09-29T09:09:21.996+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='create_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-30T00:00:00+00:00'
[2024-09-29T09:09:21.997+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-29T09:09:22.025+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-29T09:09:22.045+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-09-29T09:09:22.271+0000] {bigquery.py:470} INFO - datasetId was not specified in `dataset_reference`. Will use default value finalproject_data.
[2024-09-29T09:09:22.276+0000] {bigquery.py:470} INFO - projectId was not specified in `dataset_reference`. Will use default value madt-finalproject.
[2024-09-29T09:09:22.284+0000] {bigquery.py:481} INFO - Creating dataset: finalproject_data in project: madt-finalproject 
[2024-09-29T09:09:23.167+0000] {bigquery.py:2045} INFO - Dataset finalproject_data already exists.
[2024-09-29T09:09:23.218+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-29T09:09:23.239+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_dataset, execution_date=20240530T000000, start_date=20240929T090919, end_date=20240929T090923
[2024-09-29T09:09:23.389+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-29T09:09:23.587+0000] {taskinstance.py:3482} INFO - 9 downstream tasks scheduled from follow-on schedule check
[2024-09-29T09:09:23.600+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
