[2024-11-05T16:09:11.591+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-05T16:09:11.708+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data_pipeline_v2.create_dataset manual__2024-11-05T16:08:59.015679+00:00 [queued]>
[2024-11-05T16:09:11.714+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data_pipeline_v2.create_dataset manual__2024-11-05T16:08:59.015679+00:00 [queued]>
[2024-11-05T16:09:11.714+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-11-05T16:09:11.730+0000] {taskinstance.py:2327} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_dataset> on 2024-11-05 16:08:59.015679+00:00
[2024-11-05T16:09:11.738+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_data_pipeline_v2', 'create_dataset', 'manual__2024-11-05T16:08:59.015679+00:00', '--job-id', '3552', '--raw', '--subdir', 'DAGS_FOLDER/etl2.py', '--cfg-path', '/tmp/tmplpdp2zue']
[2024-11-05T16:09:11.739+0000] {standard_task_runner.py:91} INFO - Job 3552: Subtask create_dataset
[2024-11-05T16:09:11.741+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=21553) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-05T16:09:11.741+0000] {standard_task_runner.py:63} INFO - Started process 21600 to run task
[2024-11-05T16:09:11.777+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_data_pipeline_v2.create_dataset manual__2024-11-05T16:08:59.015679+00:00 [running]> on host 71321b93f95e
[2024-11-05T16:09:11.840+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data_pipeline_v2' AIRFLOW_CTX_TASK_ID='create_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T16:08:59.015679+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T16:08:59.015679+00:00'
[2024-11-05T16:09:11.841+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-05T16:09:11.846+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-11-05T16:09:11.850+0000] {base.py:84} INFO - Using connection ID 'my-gcp-conn' for task execution.
[2024-11-05T16:09:11.895+0000] {bigquery.py:470} INFO - datasetId was not specified in `dataset_reference`. Will use default value finalproject_data.
[2024-11-05T16:09:11.895+0000] {bigquery.py:470} INFO - projectId was not specified in `dataset_reference`. Will use default value madt-finalproject.
[2024-11-05T16:09:11.896+0000] {bigquery.py:481} INFO - Creating dataset: finalproject_data in project: madt-finalproject 
[2024-11-05T16:09:12.226+0000] {bigquery.py:2045} INFO - Dataset finalproject_data already exists.
[2024-11-05T16:09:12.241+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-05T16:09:12.247+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl_data_pipeline_v2, task_id=create_dataset, execution_date=20241105T160859, start_date=20241105T160911, end_date=20241105T160912
[2024-11-05T16:09:12.275+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-05T16:09:12.298+0000] {taskinstance.py:3482} INFO - 9 downstream tasks scheduled from follow-on schedule check
[2024-11-05T16:09:12.316+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
