[2024-09-29T14:27:40.928+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-29T14:27:40.947+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.upload_file_fact_to_warehouse scheduled__2024-08-22T00:00:00+00:00 [queued]>
[2024-09-29T14:27:40.955+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.upload_file_fact_to_warehouse scheduled__2024-08-22T00:00:00+00:00 [queued]>
[2024-09-29T14:27:40.955+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-09-29T14:27:41.053+0000] {taskinstance.py:2327} INFO - Executing <Task(GCSToGCSOperator): upload_file_fact_to_warehouse> on 2024-08-22 00:00:00+00:00
[2024-09-29T14:27:41.070+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=21203) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T14:27:41.071+0000] {standard_task_runner.py:63} INFO - Started process 21229 to run task
[2024-09-29T14:27:41.070+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'upload_file_fact_to_warehouse', 'scheduled__2024-08-22T00:00:00+00:00', '--job-id', '1860', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpfgia94x8']
[2024-09-29T14:27:41.074+0000] {standard_task_runner.py:91} INFO - Job 1860: Subtask upload_file_fact_to_warehouse
[2024-09-29T14:27:41.153+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.upload_file_fact_to_warehouse scheduled__2024-08-22T00:00:00+00:00 [running]> on host 71321b93f95e
[2024-09-29T14:27:41.342+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='upload_file_fact_to_warehouse' AIRFLOW_CTX_EXECUTION_DATE='2024-08-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-22T00:00:00+00:00'
[2024-09-29T14:27:41.344+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-29T14:27:41.364+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-29T14:27:41.377+0000] {base.py:84} INFO - Using connection ID 'my-gcp-conn' for task execution.
[2024-09-29T14:27:43.194+0000] {gcs_to_gcs.py:535} INFO - Executing copy of gs://rawdata-madt-finalproject/fact.csv to gs://storage-madt-finalproject/fact.csv
[2024-09-29T14:27:43.624+0000] {gcs.py:256} INFO - Total Bytes: 2585949 | Bytes Written: 2585949
[2024-09-29T14:27:43.624+0000] {gcs.py:264} INFO - Object fact.csv in bucket rawdata-madt-finalproject rewritten to object fact.csv in bucket storage-madt-finalproject
[2024-09-29T14:27:43.625+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-29T14:27:43.703+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl, task_id=upload_file_fact_to_warehouse, execution_date=20240822T000000, start_date=20240929T142740, end_date=20240929T142743
[2024-09-29T14:27:43.835+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-29T14:27:44.796+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T14:27:44.826+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
